# Generated by Django 5.1 on 2025-01-23 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_type', models.CharField(choices=[('stage_2', 'Speeches at second reading'), ('stage_3', 'Speeches at third reading'), ('stage_report', 'Speeches at report stage'), ('hansard_topics', 'Hansard topics')], max_length=30)),
                ('identifier', models.CharField(db_index=True, max_length=255)),
                ('summary_text', models.TextField()),
                ('summarized_statement_count', models.IntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('public', models.BooleanField(default=True, help_text='Display on site?')),
                ('metadata', models.JSONField(blank=True, default=list)),
            ],
            options={
                'unique_together': {('summary_type', 'identifier')},
            },
        ),
    ]
