# Generated by Django 5.1 on 2025-02-15 21:49

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summaries', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='summary',
            options={'verbose_name_plural': 'Summaries'},
        ),
        migrations.AddField(
            model_name='summary',
            name='latest_statement_date',
            field=models.DateField(default=datetime.date(1900, 1, 1)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='summary',
            name='summarized_statement_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SummaryPoll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.SmallIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user_ip', models.GenericIPAddressField()),
                ('summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='summaries.summary')),
                ('user_agent', models.CharField(max_length=255, blank=True)),
            ],
        ),
    ]
