# Generated by Django 5.1 on 2025-03-20 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summaries', '0002_summary_poll'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='summary_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='summary',
            name='summary_text',
            field=models.TextField(blank=True),
        ),
    ]
