# Generated by Django 5.1 on 2025-03-05 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PoliticianAlert',
        ),
    ]
