# Generated by Django 5.0.6 on 2025-01-08 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hansards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='xml_source_url',
            field=models.URLField(blank=True),
        )
    ]
