# Generated by Django 5.0.6 on 2025-01-16 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hansards', '0002_xml_source_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='OldSlugMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_slug', models.SlugField(max_length=100)),
                ('new_slug', models.SlugField(max_length=100)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hansards.document')),
            ],
            options={
                'unique_together': {('document', 'old_slug')},
            },
        ),
    ]
