# Generated by Django 5.1.5 on 2025-01-20 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hansards', '0003_add_old_slug_mapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='first_imported',
            field=models.DateTimeField(blank=True, help_text='The first time this document was imported from XML.', null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='last_imported',
            field=models.DateTimeField(blank=True, help_text='The most recent time this document was imported from XML.', null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='skip_redownload',
            field=models.BooleanField(default=False, help_text="Don't try to redownload the source."),
        )
    ]
