# Generated by Django 5.1 on 2025-02-19 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0005_add_library_summary_bool'),
        ('hansards', '0004_add_reimport_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='statement',
            name='bill_debate_stage',
            field=models.CharField(blank=True, choices=[('1', 'First reading'), ('2', 'Second reading'), ('3', 'Third reading'), ('report', 'Report stage'), ('senate', 'Senate amendments'), ('other', 'Other')], db_index=True, max_length=10),
        ),
        migrations.AddField(
            model_name='statement',
            name='bill_debated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statements_from_debates', to='bills.bill'),
        ),
        migrations.AlterField(
            model_name='statement',
            name='bills',
            field=models.ManyToManyField(blank=True, db_table='hansards_statement_bills', related_name='statements_with_mentions', to='bills.bill'),
        ),
        migrations.RenameField(
            model_name='statement',
            old_name='bills',
            new_name='mentioned_bills',
        ),
    ]
