# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-05-06 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_some_fr_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='politicianinfo',
            name='created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
