# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-05-06 11:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_polinfo_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='politicianinfo',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
