# Generated by Django 5.0.6 on 2024-05-24 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_polinfo_created_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='politician',
            name='headshot_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='polpics/thumbnail'),
        )
    ]
