# Generated by Django 5.1 on 2025-04-08 12:55

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_politician_headshot_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartyAlternateName',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.party')),
            ],
        ),
        migrations.CreateModel(
            name='RidingPostcodeCache',
            fields=[
                ('postcode', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('source', models.CharField(blank=True, max_length=30)),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('riding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.riding')),
            ],
        ),
    ]
