# Generated by Django 5.1 on 2025-04-08 12:57

from django.db import migrations

def move_party_names(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    InternalXref = apps.get_model("core", "InternalXref")
    PartyAlternateName = apps.get_model("core", "PartyAlternateName")
    Party = apps.get_model("core", "Party")
    for xref in InternalXref.objects.filter(schema='party_names'):
        PartyAlternateName.objects.get_or_create(
            name=xref.text_value,
            party=Party.objects.get(pk=xref.target_id)
        )

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_party_names_and_postcode_cache'),
    ]

    operations = [
        migrations.RunPython(move_party_names)
    ]
