# Generated by Django 5.1 on 2025-04-08 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_migrate_party_names'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InternalXref',
        )
    ]
