# Generated by Django 5.2 on 2025-05-11 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_delete_internalxref'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='politician',
            name='dob',
        )
    ]
