# Generated by Django 5.2 on 2025-05-11 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidacy',
            name='occupation',
        )
    ]
