# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-12-02 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0002_auto_20160121_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='billinsession',
            name='billstages_json',
            field=models.TextField(blank=True, null=True),
        ),
    ]
