# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-12-03 22:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0003_add_billstage_json'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billinsession',
            name='debates',
        ),
        migrations.AddField(
            model_name='billtext',
            name='summary_en',
            field=models.TextField(blank=True),
        ),
    ]
