# Generated by Django 5.1.5 on 2025-01-21 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0004_billtext_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='billinsession',
            name='library_summary_available',
            field=models.BooleanField(default=False),
        ),
    ]
