# Generated by Django 5.1 on 2025-02-20 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0005_add_library_summary_bool'),
        ('core', '0005_politician_headshot_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='billstages_json',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='legisinfo_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='library_summary_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bill',
            name='session',
            field=models.ForeignKey(default='35-1', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.session'),
            preserve_default=False,
        ),
        # I don't think any of the alternations below are meaningful, just autogenerated
        migrations.AlterField(
            model_name='bill',
            name='institution',
            field=models.CharField(choices=[('C', 'House'), ('S', 'Senate')], db_index=True, max_length=1),
        ),
        migrations.AlterField(
            model_name='bill',
            name='law',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='privatemember',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='sponsor_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.electedmember'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='sponsor_politician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.politician'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='text_docid',
            field=models.IntegerField(blank=True, help_text="The parl.gc.ca document ID of the latest version of the bill's text", null=True),
        ),
        migrations.AlterField(
            model_name='billevent',
            name='institution',
            field=models.CharField(choices=[('C', 'House'), ('S', 'Senate')], max_length=1),
        ),
        migrations.AlterField(
            model_name='membervote',
            name='vote',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('P', 'Paired'), ('A', "Didn't vote")], max_length=1),
        ),
        migrations.AlterField(
            model_name='partyvote',
            name='vote',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('P', 'Paired'), ('A', "Didn't vote"), ('F', 'Free vote')], max_length=1),
        ),
        migrations.AlterField(
            model_name='votequestion',
            name='result',
            field=models.CharField(choices=[('Y', 'Passed'), ('N', 'Failed'), ('T', 'Tie')], max_length=1),
        ),
    ]
