# Generated by Django 5.1 on 2025-02-20 12:53

from django.db import migrations

def populate_bill_fields(apps, schema_editor):
    Bill = apps.get_model('bills', 'Bill')
    BillInSession = apps.get_model('bills', 'BillInSession')
    for bill in Bill.objects.all():
        bis = BillInSession.objects.filter(bill=bill).order_by('-session__start')[0]
        bill.session = bis.session
        bill.legisinfo_id = bis.legisinfo_id
        bill.billstages_json = bis.billstages_json
        bill.library_summary_available = bis.library_summary_available
        bill.introduced = bis.introduced
        bill.sponsor_politician = bis.sponsor_politician
        bill.sponsor_member = bis.sponsor_member
        bill.save()


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0006_add_billinsession_fields_to_bill'),
    ]

    operations = [
        migrations.RunPython(populate_bill_fields),
    ]
