# Generated by Django 5.1 on 2025-02-20 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0007_populate_moved_fields_on_bill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billinsession',
            name='bill',
        ),
        migrations.RemoveField(
            model_name='billinsession',
            name='session',
        ),
        migrations.RemoveField(
            model_name='billinsession',
            name='sponsor_member',
        ),
        migrations.RemoveField(
            model_name='billinsession',
            name='sponsor_politician',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='sessions',
        ),
        migrations.DeleteModel(
            name='BillEvent',
        ),
        migrations.DeleteModel(
            name='BillInSession',
        ),
        migrations.AlterField(
            model_name='bill',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.session'),
        ),      
        migrations.AlterField(
            model_name='bill',
            name='number',
            field=models.CharField(db_index=True, max_length=10),
        ),          
    ]
