# Generated by Django 5.1 on 2025-02-20 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0008_remove_billinsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='similar_bills',
            field=models.ManyToManyField(blank=True, to='bills.bill'),
        ),
    ]
