# Generated by Django 5.1 on 2025-03-11 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0009_bill_similar_bills'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='latest_debate_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
