<div class="dropdown-pane" id="sharing-tools-dropdown">
	<div class="input-group statement-url-group">
		<input type="text" class="input-group-field statement-url" readonly="true">
		<div class="input-group-button">
			<button type="button" class="button copy-statement-url"><span class="copy-initial">Copy</span><span class="copy-success">Copied</span></button>
		</div>
	</div>
	<p>Share on <a class="twitter">Twitter</a> or <a class="facebook">Facebook</a></p>
	<p class="parl-links">Go to Parliament&rsquo;s site: <a class="transcript" target="_blank">transcript</a> or <a class="video" target="_blank">video</a>.</p>
</div>